version: '3'
services: 
  gateway.api: 
    build: ./Gateway/
    ports: 
      - 52973:80
    container_name: gateway_api
    depends_on:
      - catalog_api
      - ledger_api

  catalog_api: 
    build: ./Catalog/
    ports: 
      - 52971:80
    container_name: catalog_api

  ledger_api:
    build: ./Ledger/
    ports: 
      - 52970:80
    container_name: ledger_api

# version: '3.4'

# services:
#   gateway.api:
#     image: gateway_api
#     expose: 
#       - "80"
#     ports:
#       - "52793:80"
#     depends_on:
#       - catalog.api
#       - authentication.api
#       - ledger.api

#   catalog.api:
#     image: catalog_api
#     expose:
#       - "80"
#     ports:
#       - "52971:80"
  
#   ledger.api:
#     image: ledger_api
#     expose:
#       - "80"
#     ports:
#       - "52970:80"